//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuMaster
    {
        public int Menu_ID { get; set; }
        public string Menu_Nome { get; set; }
        public Nullable<int> Menu_Parent { get; set; }
        public string Menu_Enable { get; set; }
        public string Menu_Form { get; set; }
        public string Menu_Texto { get; set; }
        public string Menu_Tipo { get; set; }
        public string Menu_Icone { get; set; }
        public string Menu_Modulo { get; set; }
    }
}
