//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisaEntities : DbContext
    {
        public SisaEntities()
            : base("name=SisaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<menuMaster> menuMaster { get; set; }
        public virtual DbSet<TB_ACORDO> TB_ACORDO { get; set; }
        public virtual DbSet<TB_ADVOGADO> TB_ADVOGADO { get; set; }
        public virtual DbSet<TB_ALVARAS_AUTOMATIZADOS> TB_ALVARAS_AUTOMATIZADOS { get; set; }
        public virtual DbSet<TB_AND_PROCESSO> TB_AND_PROCESSO { get; set; }
        public virtual DbSet<TB_AVALISTA> TB_AVALISTA { get; set; }
        public virtual DbSet<TB_BANCO> TB_BANCO { get; set; }
        public virtual DbSet<TB_BOLETO> TB_BOLETO { get; set; }
        public virtual DbSet<TB_COD_AND_PROCESSOS> TB_COD_AND_PROCESSOS { get; set; }
        public virtual DbSet<TB_COD_DESPESA> TB_COD_DESPESA { get; set; }
        public virtual DbSet<TB_COD_EVENTO> TB_COD_EVENTO { get; set; }
        public virtual DbSet<TB_COD_HONORARIO> TB_COD_HONORARIO { get; set; }
        public virtual DbSet<TB_COMARCA> TB_COMARCA { get; set; }
        public virtual DbSet<TB_CONTATO> TB_CONTATO { get; set; }
        public virtual DbSet<TB_CONTRATO> TB_CONTRATO { get; set; }
        public virtual DbSet<TB_CUSTAS> TB_CUSTAS { get; set; }
        public virtual DbSet<TB_DADOS_REFERENCIA> TB_DADOS_REFERENCIA { get; set; }
        public virtual DbSet<TB_DEPOSITOS_JUDICIAIS> TB_DEPOSITOS_JUDICIAIS { get; set; }
        public virtual DbSet<TB_DESPESA> TB_DESPESA { get; set; }
        public virtual DbSet<TB_DIC_DADOS> TB_DIC_DADOS { get; set; }
        public virtual DbSet<TB_DOMINIO> TB_DOMINIO { get; set; }
        public virtual DbSet<TB_ENDERECO> TB_ENDERECO { get; set; }
        public virtual DbSet<TB_FERIADO> TB_FERIADO { get; set; }
        public virtual DbSet<TB_GRUPO> TB_GRUPO { get; set; }
        public virtual DbSet<TB_HONORARIO> TB_HONORARIO { get; set; }
        public virtual DbSet<TB_HORARIOS> TB_HORARIOS { get; set; }
        public virtual DbSet<TB_INDICE> TB_INDICE { get; set; }
        public virtual DbSet<TB_LOGIN> TB_LOGIN { get; set; }
        public virtual DbSet<TB_MANDADOSOFICIAIS> TB_MANDADOSOFICIAIS { get; set; }
        public virtual DbSet<TB_MOVIMENTACOES> TB_MOVIMENTACOES { get; set; }
        public virtual DbSet<TB_NOTAS_EXPEDIENTE> TB_NOTAS_EXPEDIENTE { get; set; }
        public virtual DbSet<TB_NOTIFICACAO> TB_NOTIFICACAO { get; set; }
        public virtual DbSet<TB_OBSERVACAO_JUDICIAL> TB_OBSERVACAO_JUDICIAL { get; set; }
        public virtual DbSet<TB_OBSERVACAO_PREJUD> TB_OBSERVACAO_PREJUD { get; set; }
        public virtual DbSet<TB_PARTES_ENVOLVIDAS> TB_PARTES_ENVOLVIDAS { get; set; }
        public virtual DbSet<TB_PERMISSOES> TB_PERMISSOES { get; set; }
        public virtual DbSet<TB_PESSOA> TB_PESSOA { get; set; }
        public virtual DbSet<TB_PETICOES> TB_PETICOES { get; set; }
        public virtual DbSet<TB_PROCESSO> TB_PROCESSO { get; set; }
        public virtual DbSet<TB_SISTEMA> TB_SISTEMA { get; set; }
        public virtual DbSet<TB_TELA> TB_TELA { get; set; }
        public virtual DbSet<TB_TIPO_ACAO> TB_TIPO_ACAO { get; set; }
        public virtual DbSet<TB_TITULO> TB_TITULO { get; set; }
        public virtual DbSet<TB_UF> TB_UF { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
        public virtual DbSet<TB_VEICULO> TB_VEICULO { get; set; }
        public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual DbSet<View_Dias_Atraso> View_Dias_Atraso { get; set; }
        public virtual DbSet<vw_busca_cliente_banco> vw_busca_cliente_banco { get; set; }
        public virtual DbSet<vw_listacontratos> vw_listacontratos { get; set; }
        public virtual DbSet<VW_TITULOS> VW_TITULOS { get; set; }
        public virtual DbSet<VW_CONTRATOS> VW_CONTRATOS { get; set; }
        public virtual DbSet<VW_PROCESSO> VW_PROCESSO { get; set; }
        public virtual DbSet<TB_LOCALIZADOR> TB_LOCALIZADOR { get; set; }
        public virtual DbSet<TB_HISTORICO> TB_HISTORICO { get; set; }
    }
}
