//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ADVOGADO
    {
        public int CD_ADVOGADO { get; set; }
        public string NM_ADVOGADO { get; set; }
        public string CD_OAB { get; set; }
        public string AN_TELEFONE { get; set; }
        public string AN_EMAIL { get; set; }
        public string NM_ESCRITORIO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
