//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AVALISTA
    {
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public int ID_BANCO { get; set; }
        public int SQ_AVALISTA { get; set; }
        public string NM_AVALISTA { get; set; }
        public string IN_F_J_AVALISTA { get; set; }
        public string AN_ENDERECO { get; set; }
        public string AN_CIDADE { get; set; }
        public string AN_BAIRRO { get; set; }
        public string AN_CEP { get; set; }
        public string CD_UF { get; set; }
        public string AN_TELEFONE { get; set; }
        public string AN_CELULAR { get; set; }
        public string AN_REF_AVALISTA1 { get; set; }
        public string AN_REF_AVALISTA2 { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
