//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUDIENCIAS
    {
        public int ID_AUDIENCIA { get; set; }
        public int ID_PROCESSO { get; set; }
        public Nullable<int> CD_CLIENTE { get; set; }
        public Nullable<int> NR_OPERACAO { get; set; }
        public string CD_CONTRATO { get; set; }
        public string NR_PROCESSO_CNJ { get; set; }
        public string NR_PROCESSO_THEMIS { get; set; }
        public Nullable<System.DateTime> DATA_AUDIENCIA { get; set; }
        public string TEXTO_AUDIENCIA { get; set; }
    }
}
