//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AND_PROCESSO
    {
        public int ID_ANDAMENTO { get; set; }
        public int ID_PROCESSO { get; set; }
        public int CD_CLIENTE { get; set; }
        public int ID_BANCO { get; set; }
        public string CD_ANDAMENTO { get; set; }
        public System.DateTime DT_ANDAMENTO { get; set; }
        public string DS_ANDAMENTO { get; set; }
        public Nullable<int> FL_FIM_ACAO { get; set; }
        public Nullable<int> NR_C_FIN { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
