//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ACORDO
    {
        public int CD_CLIENTE { get; set; }
        public int ID_BANCO { get; set; }
        public string ID_CONTRATO { get; set; }
        public int NR_PARCELA { get; set; }
        public string NR_ACORDO { get; set; }
        public string CD_BOLETO { get; set; }
        public Nullable<System.DateTime> DT_VCTO { get; set; }
        public Nullable<decimal> VL_TITULO { get; set; }
        public Nullable<System.DateTime> DT_PAGTO { get; set; }
        public Nullable<decimal> VL_HONORARIOS { get; set; }
        public Nullable<decimal> VL_CUSTAS { get; set; }
        public Nullable<decimal> VL_TARIFA { get; set; }
        public Nullable<decimal> VL_TOTAL_GERAL { get; set; }
        public string TX_OBSERVACAO { get; set; }
        public string AN_TIPO_PAGTO { get; set; }
        public Nullable<System.DateTime> DT_ACORDO { get; set; }
        public string HR_ACORDO { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<decimal> VL_BANCO { get; set; }
        public Nullable<decimal> VL_REPASSE { get; set; }
        public Nullable<System.DateTime> DT_REPASSE { get; set; }
        public Nullable<System.DateTime> HR_REPASSE { get; set; }
        public string CD_USUARIO_REPASSE { get; set; }
        public string AN_TIPO_ACORDO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
