//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANCO
    {
        public int ID_BANCO { get; set; }
        public string CD_BANCO { get; set; }
        public string DS_BANCO { get; set; }
        public string AN_ENDERECO { get; set; }
        public string AN_CIDADE { get; set; }
        public string CD_UF { get; set; }
        public string AN_CNPJ { get; set; }
        public string AN_INS_EST { get; set; }
        public string CD_AGENCIA { get; set; }
        public string CD_CEDENTE { get; set; }
        public Nullable<double> FT_IND_BANCO { get; set; }
        public Nullable<double> FT_IND_JURIDICO { get; set; }
        public Nullable<decimal> FT_IND_DESCONTO { get; set; }
        public Nullable<decimal> FT_IND_JUROS { get; set; }
        public Nullable<decimal> VL_ENCARGOS { get; set; }
        public Nullable<decimal> VL_ESCRITORIO { get; set; }
        public Nullable<decimal> VL_NOTIFICACAO { get; set; }
        public Nullable<decimal> VL_HONORARIOS { get; set; }
        public Nullable<int> QT_DIAS_NOTIFICACAO { get; set; }
        public Nullable<int> NR_RECIBO { get; set; }
        public Nullable<int> NR_BOLETO { get; set; }
        public Nullable<int> NR_BORDERO { get; set; }
        public Nullable<int> NR_NOTIFICACAO { get; set; }
        public Nullable<int> NR_LOTE { get; set; }
        public Nullable<int> QT_DIAS_AJUIZAMENTO { get; set; }
        public Nullable<int> QT_DIAS_CARTORIO { get; set; }
        public Nullable<decimal> VL_META { get; set; }
        public Nullable<decimal> VL_LOCALIZADOR { get; set; }
        public Nullable<decimal> VL_MULTA { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
