//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BOLETO
    {
        public int CD_CLIENTE { get; set; }
        public int ID_BANCO { get; set; }
        public int NR_PARCELA { get; set; }
        public string CD_BOLETO { get; set; }
        public Nullable<System.DateTime> DT_PREV_DEPOSITO { get; set; }
        public Nullable<System.DateTime> DT_VCTO { get; set; }
        public Nullable<decimal> VL_TITULO { get; set; }
        public Nullable<System.DateTime> DT_PAGTO { get; set; }
        public Nullable<decimal> VL_ENCARGOS { get; set; }
        public Nullable<decimal> VL_ESCRITORIO { get; set; }
        public Nullable<decimal> VL_NOTIFICACAO { get; set; }
        public Nullable<decimal> VL_HONORARIOS { get; set; }
        public Nullable<decimal> VL_CPMF { get; set; }
        public Nullable<decimal> VL_LOCALIZADOR { get; set; }
        public Nullable<decimal> VL_CUSTAS { get; set; }
        public Nullable<decimal> VL_DESP_EXTRA { get; set; }
        public Nullable<decimal> VL_DESPESA { get; set; }
        public Nullable<decimal> VL_TARIFA_BANCARIA { get; set; }
        public Nullable<decimal> VL_MULTA { get; set; }
        public Nullable<decimal> VL_PAGTO_S_HONO { get; set; }
        public Nullable<decimal> VL_PAGTO_C_HONO { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public Nullable<decimal> VL_TOTAL { get; set; }
        public Nullable<decimal> FT_IND_DESCONTO { get; set; }
        public Nullable<decimal> VL_POR_DIA { get; set; }
        public Nullable<decimal> VL_JUROS { get; set; }
        public Nullable<decimal> FT_IND_BANCO { get; set; }
        public Nullable<decimal> FT_IND_JURIDICO { get; set; }
        public Nullable<decimal> VL_COMISSIONAMENTO { get; set; }
        public Nullable<decimal> VL_COMISS_PERM { get; set; }
        public string VL_TOTAL_GERAL { get; set; }
        public Nullable<int> NR_DIAS_ATRASO { get; set; }
        public string TX_OBSERVACAO { get; set; }
        public string TX_OBSERVACAO2 { get; set; }
        public string TX_OBSERVACAO3 { get; set; }
        public string AN_TX_CONTRATO { get; set; }
        public Nullable<int> NR_LOTE { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA { get; set; }
        public Nullable<int> FL_IMPRIMIR { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string AN_CAMPO_1 { get; set; }
        public string AN_DIGITO_1 { get; set; }
        public string AN_CAMPO_2 { get; set; }
        public string AN_DIGITO_2 { get; set; }
        public string AN_CAMPO_3 { get; set; }
        public string AN_DIGITO_3 { get; set; }
        public string AN_DIGITO_GERAL { get; set; }
        public string AN_CODIGO_BARRA { get; set; }
        public string CD_AGENCIA { get; set; }
        public string CD_CEDENTE { get; set; }
        public string NM_CEDENTE { get; set; }
        public string CD_REPR_NUMERICA { get; set; }
        public string IN_TIPO_BLOQUETO { get; set; }
        public string CD_ERRO { get; set; }
        public string AN_DESCR_ERRO { get; set; }
        public Nullable<System.DateTime> DT_RETORNO { get; set; }
        public Nullable<System.DateTime> DT_BOLETO_PAGO { get; set; }
        public string IN_TIPO_COMISS { get; set; }
        public Nullable<int> NR_INCONSISTENCIA { get; set; }
        public Nullable<System.DateTime> DT_CONFIRMA_PAGTO { get; set; }
        public Nullable<int> IN_FAX_TRANSMITIDO { get; set; }
        public string NR_FAX { get; set; }
        public string AN_DESCR_BOLETO { get; set; }
        public string AN_CONTRATOS_BOLETO { get; set; }
        public string AN_PARCELAS_BOLETO { get; set; }
        public string AN_COD_AUTORIZACAO { get; set; }
        public string CD_PROGRAMA { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
        public string CD_USUARIO_EXC { get; set; }
    }
}
