//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DIC_DADOS
    {
        public string CD_MODULO { get; set; }
        public string CD_TABELA { get; set; }
        public string CD_CAMPO { get; set; }
        public string IN_TP_DADO { get; set; }
        public string IN_TP_OBJETO { get; set; }
        public string DS_CAMPO { get; set; }
        public string AN_HELP { get; set; }
        public Nullable<int> FL_OBRIGATORIO { get; set; }
    }
}
