//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DADOS_REFERENCIA
    {
        public int CD_CLIENTE { get; set; }
        public string AN_CONTATO_TEL_RES { get; set; }
        public string AN_NOME_CONJUGE { get; set; }
        public string AN_NOME_PRIM_REFERENCIA { get; set; }
        public string AN_TP_PARENTESCO_PRIM_PES { get; set; }
        public string AN_NOME_SEG_REFERENCIA { get; set; }
        public string AN_TP_PARENTESCO_SEG_PES { get; set; }
        public string AN_TIPO_OPERACAO { get; set; }
        public string AN_NUCLEO { get; set; }
        public Nullable<int> CD_LOJA { get; set; }
        public string AN_NOME_LOJA { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public string AN_NOME_FILIAL { get; set; }
        public Nullable<int> CD_GRUPO { get; set; }
        public string AN_NOME_GRUPO { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public string AN_NOME_EMPRESA { get; set; }
        public string AN_TIPO_SEGURO { get; set; }
        public string AN_LOCAL_TRABALHO { get; set; }
        public string AN_CARGO_TRABALHO { get; set; }
        public Nullable<int> FL_PESQUISA { get; set; }
        public Nullable<System.DateTime> DT_PESQUISA { get; set; }
        public Nullable<int> FL_LOCALIZADOR { get; set; }
        public Nullable<System.DateTime> DT_LOCALIZADOR { get; set; }
        public string AN_NOME_LOCALIZADOR { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
