//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DESPESA
    {
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public int SQ_DESPESA { get; set; }
        public string DS_DESPESA { get; set; }
        public Nullable<int> FL_COMPENSACAO { get; set; }
        public Nullable<System.DateTime> DT_COMPENSACAO { get; set; }
        public Nullable<int> NR_PARCELA { get; set; }
        public string CD_DESPESA { get; set; }
        public Nullable<decimal> VL_DESPESA { get; set; }
        public Nullable<int> FL_STATUS_PGTO { get; set; }
        public Nullable<System.DateTime> DT_PAGTO { get; set; }
        public Nullable<int> NR_DOC_NF { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_BANCO { get; set; }
        public Nullable<System.DateTime> DT_PAGTO_PREST { get; set; }
        public Nullable<int> NR_EMPRESA { get; set; }
        public Nullable<System.DateTime> DT_MOVIMENTO { get; set; }
        public Nullable<decimal> NR_CGC_CARTORIO { get; set; }
        public Nullable<int> NR_LOTE_INTERNO { get; set; }
        public Nullable<decimal> NR_VALE { get; set; }
        public string AN_JUSTIFICATIVA_MANUAL { get; set; }
        public Nullable<System.DateTime> DT_JUSTIFICATIVA { get; set; }
        public Nullable<int> NR_BORDERO { get; set; }
        public string AN_GRERJ { get; set; }
        public string AN_PROCESSO { get; set; }
        public string NM_COMARCA { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
        public int ID_BANCO { get; set; }
    }
}
