//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEPOSITOS_JUDICIAIS
    {
        public int ID_DEPOSITO { get; set; }
        public int ID_PROCESSO { get; set; }
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public System.DateTime DATA_EMISSAO { get; set; }
        public string NR_GUIA { get; set; }
        public Nullable<decimal> VLR_GUIA { get; set; }
        public Nullable<System.DateTime> DATA_DEPOSITO { get; set; }
        public string DEPOSITANTE { get; set; }
    }
}
