//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ENDERECO
    {
        public int ID_ENDERECO { get; set; }
        public int CD_CLIENTE { get; set; }
        public int SQ_ENDERECO { get; set; }
        public string IN_ENDERECO { get; set; }
        public string AN_ORIGEM { get; set; }
        public Nullable<int> FL_ATIVO { get; set; }
        public string AN_ENDERECO { get; set; }
        public Nullable<int> NR_ENDERECO { get; set; }
        public string AN_COMPLEMENTO { get; set; }
        public string AN_BAIRRO { get; set; }
        public string AN_CIDADE { get; set; }
        public string CD_UF { get; set; }
        public string AN_CEP { get; set; }
        public string AN_NOME_EMPRESA { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
