//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMAIL
    {
        public int ID_EMAIL { get; set; }
        public int CD_CLIENTE { get; set; }
        public Nullable<int> SQ_EMAIL { get; set; }
        public string AN_EMAIL { get; set; }
        public string AN_RESPONSAVEL { get; set; }
        public string AN_ORIGEM { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
