//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EVENTO
    {
        public int ID_EVENTO { get; set; }
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public int ID_BANCO { get; set; }
        public System.DateTime DT_EVENTO { get; set; }
        public string HR_EVENTO { get; set; }
        public int NR_PARCELA { get; set; }
        public string CD_USUARIO_RESP { get; set; }
        public string CD_USUARIO_OPER { get; set; }
        public Nullable<System.DateTime> DT_EVENTO_REAL { get; set; }
        public string HR_INI { get; set; }
        public string HR_FIM { get; set; }
        public string IN_SIT_CONTATO { get; set; }
        public string CD_TIPO_EVENTO { get; set; }
        public string AN_DS_EVENTO_ASSUNTO { get; set; }
        public string AN_OBS_EVENTO_ASSUNTO { get; set; }
        public Nullable<int> NR_PRIORIDADE { get; set; }
        public string HR_TEMPO_LIGACAO { get; set; }
        public string HR_HORA_MARCADA { get; set; }
        public Nullable<int> FL_EXPORTADO_EVENTO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_BANCO { get; set; }
        public string AN_ARQUIVO_ENVIO { get; set; }
        public string NR_DDD { get; set; }
        public string NR_TELEFONE { get; set; }
        public string IN_LIGACAO_EFETUADA { get; set; }
        public string AN_STATUS { get; set; }
        public string AN_SITUACAO_CONTRATO { get; set; }
        public string CD_PROGRAMA { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USARIO_ALT { get; set; }
    }
}
