//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HONORARIO
    {
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public int SQ_HONORARIOS { get; set; }
        public Nullable<decimal> VL_HONORARIOS { get; set; }
        public Nullable<int> NR_DOC_NF { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_BANCO { get; set; }
        public Nullable<System.DateTime> DT_MOVIMENTO { get; set; }
        public Nullable<int> FL_REEMBOLSAVEL { get; set; }
        public string NM_CLIENTE { get; set; }
        public string TX_OBS { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
        public int ID_BANCO { get; set; }
    }
}
