//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HORARIOS
    {
        public int ID_HORARIO { get; set; }
        public int CODIGO { get; set; }
        public string HORARIO_INICIAL { get; set; }
        public string HORARIO_FINAL { get; set; }
        public string HORARIO_INTERVALO_INICIAL { get; set; }
        public string HORARIO_INTERVALO_FINAL { get; set; }
        public string HORAS_DIA { get; set; }
    }
}
