//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INDICE
    {
        public int ID_INDICE { get; set; }
        public string NM_BANCO { get; set; }
        public string TIPO { get; set; }
        public string INTERVALO { get; set; }
        public Nullable<decimal> FT_DESC_PARCELA { get; set; }
        public Nullable<decimal> FT_DESC_PRINCIPAL { get; set; }
        public Nullable<decimal> FT_JUROS { get; set; }
        public Nullable<decimal> FT_MULTA { get; set; }
        public Nullable<decimal> FT_HONORARIOS { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
