//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOGIN
    {
        public int Login_ID { get; set; }
        public Nullable<int> Login_Usuario { get; set; }
        public string Login_PC { get; set; }
        public Nullable<System.DateTime> Login_Data { get; set; }
        public string Login_IP { get; set; }
        public string Login_MAC { get; set; }
        public Nullable<System.TimeSpan> Login_Hora { get; set; }
    }
}
