//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOCALIZADOR
    {
        public int ID_LOCALIZADOR { get; set; }
        public string NM_LOCALIZADOR { get; set; }
        public string AN_CPF { get; set; }
        public string AN_ENDERECO { get; set; }
        public string AN_TELEFONE { get; set; }
        public string AN_EMAIL { get; set; }
    }
}
