//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MOVIMENTACOES
    {
        public int ID_MOVIMENTACAO { get; set; }
        public int ID_PROCESSO { get; set; }
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public System.DateTime DATA_MOVIMENTACAO { get; set; }
        public string TEXTO_MOVIMENTACAO { get; set; }
    }
}
