//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTIFICACAO
    {
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public int SQ_NOTIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_GERACAO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO { get; set; }
        public Nullable<System.DateTime> DT_RETORNO { get; set; }
        public Nullable<System.DateTime> DT_RESPOSTA { get; set; }
        public string AN_TIPO_NOTIFICACAO { get; set; }
        public Nullable<decimal> VL_NOTIFICACAO { get; set; }
        public Nullable<int> NR_NOTIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_PAGTO_NOTIFICACAO { get; set; }
        public Nullable<int> NR_PARCELA { get; set; }
        public string AN_RESULTADO { get; set; }
        public Nullable<int> NR_RETORNO { get; set; }
        public string AN_RENOTIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
