//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PARTES_ENVOLVIDAS
    {
        public int ID_PARTES_ENVOLVIDAS { get; set; }
        public int ID_PROCESSO { get; set; }
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public string AN_REQUERENTE { get; set; }
        public string AN_ADVOGADO_REQUERENTE { get; set; }
        public string AN_REQUERIDO { get; set; }
        public string AN_ADVOGADO_REQUERIDO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
