//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROCESSO
    {
        public int ID_PROCESSO { get; set; }
        public int CD_CLIENTE { get; set; }
        public int ID_BANCO { get; set; }
        public int ID_CONTRATO { get; set; }
        public string AN_PROCESSO { get; set; }
        public string AN_CNJ { get; set; }
        public string IN_TP_ACAO { get; set; }
        public string IN_TP_PROCESSO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public Nullable<int> CD_ADVOGADO { get; set; }
        public Nullable<System.DateTime> DT_DISTRIBUICAO { get; set; }
        public string AN_ESTADO { get; set; }
        public string NM_COMARCA { get; set; }
        public Nullable<decimal> VL_CUSTAS { get; set; }
        public string CD_VARA { get; set; }
        public Nullable<decimal> VL_ACAO { get; set; }
        public string IN_CHANCE_PERDA { get; set; }
        public Nullable<System.DateTime> DT_COPIA_RECEB { get; set; }
        public Nullable<System.DateTime> DT_ORIGINAL_RECEB { get; set; }
        public Nullable<System.DateTime> DT_MINUTA_PROTOCOL { get; set; }
        public string IN_FASE_PROCESSUAL { get; set; }
        public string IN_LIMINAR { get; set; }
        public Nullable<int> QT_ALVARA_LEV { get; set; }
        public Nullable<decimal> VL_ALVARA_LEV { get; set; }
        public Nullable<decimal> VL_TOT_ALVARA_LEV { get; set; }
        public Nullable<int> QT_DEPOSITO_DEP { get; set; }
        public Nullable<decimal> VL_DEPOSITO_DEP { get; set; }
        public string IN_TIPO_ACORDO { get; set; }
        public Nullable<decimal> VL_TOTAL_ACORDO { get; set; }
        public Nullable<decimal> VL_ENTRADA_ACORDO { get; set; }
        public Nullable<int> QT_PARCELAS_ACORDO { get; set; }
        public Nullable<decimal> VL_PARCELA { get; set; }
        public Nullable<System.DateTime> DT_VCTO { get; set; }
        public string AN_SITUACAO_ACORDO { get; set; }
        public string AN_PRESTACAO_CONTAS { get; set; }
        public string AN_INSTANCIA { get; set; }
        public string AN_AGRAVO { get; set; }
        public Nullable<decimal> VL_PROVISIONAMENTO { get; set; }
        public Nullable<System.DateTime> DT_AUDIENCIA { get; set; }
        public string AN_RAZAO_ENCERRAMENTO { get; set; }
        public string AN_VL_CONDENACAO { get; set; }
        public string AN_IDENTIFICACAO_ALVARA { get; set; }
        public string AN_SITUACAO_PROCESSUAL { get; set; }
        public Nullable<System.DateTime> DT_ANDAMENTO { get; set; }
        public string AN_TIPO_ENVIO { get; set; }
        public Nullable<int> NR_CODIGO { get; set; }
        public string AN_SENTENCA { get; set; }
        public string AN_VL_DISCUTIDO_EXTRA { get; set; }
        public string AN_OBSERVACAO { get; set; }
        public string AN_VL_ENTRADA_ACORDO_ESP { get; set; }
        public string AN_FASE { get; set; }
        public Nullable<decimal> VL_ALVARA_ACORDO { get; set; }
        public string AN_SPC_SERASA { get; set; }
        public string IN_RET_ACAO_COB { get; set; }
        public string IN_PEND_LIQ_SENT { get; set; }
        public string AN_PROVIDENCIAS { get; set; }
        public string AN_DESCRICAO { get; set; }
        public string AN_VL_ALVARA_EXTRA { get; set; }
        public string AN_SITUACAO_PROCESSO { get; set; }
        public Nullable<System.DateTime> DT_ENCERRAMENTO { get; set; }
        public string AN_SETOR_RESPONSAVEL { get; set; }
        public string AN_JUSTICA { get; set; }
        public string NR_PASTA { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
