//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PESSOA
    {
        public int ID_PESSOA { get; set; }
        public int CD_CLIENTE { get; set; }
        public string NM_PESSOA { get; set; }
        public string IN_F_J { get; set; }
        public string AN_CNPJ_CPF { get; set; }
        public string AN_CLUSTER_RATING { get; set; }
        public string AN_TX_CARTEIRA { get; set; }
        public string AN_CARTEIRA { get; set; }
        public string AN_TX_INFORMATIVO1 { get; set; }
        public string AN_TX_INFORMATIVO2 { get; set; }
        public string AN_RECURSO_AUXILIAR { get; set; }
        public string AN_MES_BASE { get; set; }
        public string AN_PARCELA_INIBIDA { get; set; }
        public string AN_CREDITO { get; set; }
        public string AN_OCUPACAO { get; set; }
        public string AN_CARGO { get; set; }
        public string AN_RG { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_RG { get; set; }
        public string AN_ORGAO_EMISSAO_RG { get; set; }
        public string CD_UF_RG { get; set; }
        public string AN_SEXO { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO { get; set; }
        public string AN_NATURALIDADE { get; set; }
        public string AN_NACIONALIDADE { get; set; }
        public string AN_ESTADO_CIVIL { get; set; }
        public string AN_NOME_CONJUGE { get; set; }
        public string AN_NOME_PAI { get; set; }
        public string AN_NOME_MAE { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
