//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TITULO
    {
        public int CD_CLIENTE { get; set; }
        public int ID_BANCO { get; set; }
        public int ID_CONTRATO { get; set; }
        public int NR_PARCELA { get; set; }
        public Nullable<int> NR_DIAS_ATRASO { get; set; }
        public string CD_BOLETO { get; set; }
        public Nullable<System.DateTime> DT_VCTO { get; set; }
        public Nullable<decimal> VL_TITULO { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO { get; set; }
        public Nullable<System.DateTime> DT_PRIM_NOTIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_RECEBIMENTO { get; set; }
        public Nullable<System.DateTime> DT_CREDITO { get; set; }
        public Nullable<System.DateTime> DT_REPASSE { get; set; }
        public Nullable<System.DateTime> DT_BAIXA { get; set; }
        public Nullable<int> FL_BAIXA_MANUAL { get; set; }
        public string AN_ARQUIVO_ENVIO { get; set; }
        public Nullable<int> NR_DIAS_PAGTO { get; set; }
        public Nullable<System.DateTime> DT_BANCO_PAGTO { get; set; }
        public string CD_PROGRAMA_EXC { get; set; }
        public string AN_MOTIVO_EXC { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
        public string CD_USUARIO_EXC { get; set; }
    }
}
