//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_ACAO
    {
        public int ID_TIPO_ACAO { get; set; }
        public string AN_TIPO_ACAO { get; set; }
        public string AN_TIPO { get; set; }
    }
}
