//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string CD_USUARIO { get; set; }
        public Nullable<int> GRUPO_USUARIO { get; set; }
        public string AN_SENHA { get; set; }
        public string IN_NIVEL { get; set; }
        public string NM_NOME { get; set; }
        public string AN_EMAIL { get; set; }
        public Nullable<int> CD_HORARIO { get; set; }
        public Nullable<int> FL_LOCALIZADOR { get; set; }
        public Nullable<int> FL_PESQUISA { get; set; }
        public Nullable<int> FL_GESTOR { get; set; }
        public Nullable<int> FL_ADVOGADO { get; set; }
        public Nullable<int> FL_ACIONADOR { get; set; }
        public Nullable<int> FL_FINANCEIRO { get; set; }
        public Nullable<int> FL_ADMINISTRADOR { get; set; }
        public Nullable<int> FL_LIBERA_HONORARIOS { get; set; }
        public Nullable<int> FL_IMPRIME_RECIBO { get; set; }
        public Nullable<int> FL_ATIVO { get; set; }
        public Nullable<int> FL_TROCA_SENHA { get; set; }
        public Nullable<int> FL_INCLUI_ALTERA_PARCELA { get; set; }
        public Nullable<int> FL_ALTERA_DADOS_ACORDO { get; set; }
        public Nullable<int> FL_EXCLUI_CLIENTE { get; set; }
        public Nullable<int> FL_IMPRIME_BOLETO { get; set; }
        public Nullable<int> FL_BASE_ELETRONICA { get; set; }
        public Nullable<int> FL_EMITE_MINUTAS { get; set; }
        public Nullable<int> FL_EXCLUI_DADOS_PROCESSO { get; set; }
        public Nullable<int> FL_AUTORIZA_DESCONTO { get; set; }
        public Nullable<int> FL_LIBERA_CUSTAS { get; set; }
        public Nullable<int> FL_LIBERA_ESTORNO_PAGAMENTO { get; set; }
        public Nullable<int> QT_EVENTOS_DIA { get; set; }
        public string TEMPO_EVENTOS_DIA { get; set; }
        public Nullable<int> QT_BOLETOS_DIA { get; set; }
        public Nullable<decimal> VL_META { get; set; }
        public Nullable<int> NR_FILIAL { get; set; }
        public string AN_GESTOR { get; set; }
        public string NM_CEDENTE { get; set; }
        public string AN_CIDADE { get; set; }
        public string AN_ENDERECO { get; set; }
        public Nullable<System.DateTime> DT_ALTERA_SENHA { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
        public string FL_ACESSA_ALFA { get; set; }
        public string FL_ACESSA_DAYCOVAL { get; set; }
        public string FL_ACESSA_FICSA { get; set; }
        public string FL_ACESSA_OMNI { get; set; }
        public string FL_ACESSA_RENNER { get; set; }
        public string FL_ACESSA_SULFINANCEIRA { get; set; }
        public string FL_ACESSA_OUTROBANCOS { get; set; }
        public Nullable<decimal> VL_META_ALFA { get; set; }
        public Nullable<decimal> VL_META_DAYCOVAL { get; set; }
        public Nullable<decimal> VL_META_FICSA { get; set; }
        public Nullable<decimal> VL_META_RENNER { get; set; }
        public Nullable<decimal> VL_META_OMNI { get; set; }
        public Nullable<decimal> VL_META_SULFINANCEIRA { get; set; }
        public Nullable<decimal> VL_META_OUTROSBANCOS { get; set; }
        public Nullable<int> NR_RECIBO { get; set; }
        public Nullable<int> NR_BOLETO { get; set; }
        public string NR_CNPJ_CARTORIO { get; set; }
        public Nullable<int> FL_EXCLUI_PARCELA { get; set; }
        public string AN_TIPO_SELECAO { get; set; }
    }
}
