//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VEICULO
    {
        public int CD_CLIENTE { get; set; }
        public int ID_CONTRATO { get; set; }
        public string AN_MARCA_VEIC { get; set; }
        public string AN_MODELO_VEIC { get; set; }
        public Nullable<int> NR_COD_SEGURADORA { get; set; }
        public string AN_MONTADORA_VEIC { get; set; }
        public string AN_ANO_FAB_VEIC { get; set; }
        public string AN_ANO_MODELO_VEIC { get; set; }
        public string AN_COR_VEIC { get; set; }
        public string AN_PLACA_VEIC { get; set; }
        public string CD_UF_VEIC { get; set; }
        public string AN_CHASSI_VEIC { get; set; }
        public string CD_RENAVAN { get; set; }
        public string CD_COMBUST_VEIC { get; set; }
        public string AN_CERTIF_VEIC { get; set; }
        public Nullable<System.DateTime> DT_ENT_VEIC_GARAGEM { get; set; }
        public Nullable<System.DateTime> DT_VCTO_VEIC_GARAGEM { get; set; }
        public string AN_END_GARAGEM { get; set; }
        public string AN_OBS_GARAGEM { get; set; }
        public string AN_DEPOSITARIO_GARAGEM { get; set; }
        public string AN_GUINCHO { get; set; }
        public string AN_FONE_GARAGEM { get; set; }
        public string AN_LOCAL_DEPOSITO { get; set; }
        public Nullable<System.DateTime> DT_APREENSAO { get; set; }
        public Nullable<int> FL_VEIC_REMOVIDO { get; set; }
        public Nullable<decimal> VL_PAGO_REMOVIDO { get; set; }
        public Nullable<System.DateTime> DT_SAIDA_GARAGEM { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
    }
}
