//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_listacontratos
    {
        public Nullable<int> dia_atraso { get; set; }
        public int CD_CLIENTE { get; set; }
        public string NM_BANCO { get; set; }
        public int NR_OPERACAO { get; set; }
        public string CD_CONTRATO { get; set; }
        public int NR_PARCELA { get; set; }
        public Nullable<int> NR_DIAS_ATRASO { get; set; }
        public string CD_BOLETO { get; set; }
        public Nullable<System.DateTime> DT_VCTO { get; set; }
        public Nullable<decimal> VL_TITULO { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO { get; set; }
        public Nullable<System.DateTime> DT_PRIM_NOTIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_RECEBIMENTO { get; set; }
        public Nullable<System.DateTime> DT_CREDITO { get; set; }
        public Nullable<System.DateTime> DT_REPASSE { get; set; }
        public Nullable<System.DateTime> DT_BAIXA { get; set; }
        public Nullable<int> FL_BAIXA_MANUAL { get; set; }
        public string AN_ARQUIVO_ENVIO { get; set; }
        public Nullable<int> NR_DIAS_PAGTO { get; set; }
        public Nullable<System.DateTime> DT_BANCO_PAGTO { get; set; }
        public string CD_PROGRAMA_EXC { get; set; }
        public string AN_MOTIVO_EXC { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string CD_USUARIO_INC { get; set; }
        public string CD_USUARIO_ALT { get; set; }
        public string CD_USUARIO_EXC { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string NM_PESSOA { get; set; }
        public string IN_F_J { get; set; }
        public string AN_CNPJ_CPF { get; set; }
        public string AN_OCUPACAO { get; set; }
        public string AN_CARGO { get; set; }
        public string AN_RG { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_RG { get; set; }
        public string AN_ORGAO_EMISSAO_RG { get; set; }
        public string CD_UF_RG { get; set; }
        public string AN_SEXO { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO { get; set; }
        public string AN_NATURALIDADE { get; set; }
        public string AN_NACIONALIDADE { get; set; }
        public string AN_ESTADO_CIVIL { get; set; }
        public string AN_NOME_CONJUGE { get; set; }
        public string AN_NOME_PAI { get; set; }
        public string AN_NOME_MAE { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
        public Nullable<System.DateTime> Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public string Expr7 { get; set; }
        public Nullable<int> Expr8 { get; set; }
        public string Expr9 { get; set; }
        public Nullable<System.DateTime> DT_PREV_DEPOSITO { get; set; }
        public Nullable<System.DateTime> Expr10 { get; set; }
        public Nullable<decimal> Expr11 { get; set; }
        public Nullable<System.DateTime> DT_PAGTO { get; set; }
        public Nullable<decimal> VL_ENCARGOS { get; set; }
        public Nullable<decimal> VL_ESCRITORIO { get; set; }
        public Nullable<decimal> VL_NOTIFICACAO { get; set; }
        public Nullable<decimal> VL_HONORARIOS { get; set; }
        public Nullable<decimal> VL_CPMF { get; set; }
        public Nullable<decimal> VL_LOCALIZADOR { get; set; }
        public Nullable<decimal> VL_CUSTAS { get; set; }
        public Nullable<decimal> VL_DESP_EXTRA { get; set; }
        public Nullable<decimal> VL_DESPESA { get; set; }
        public Nullable<decimal> VL_TARIFA_BANCARIA { get; set; }
        public Nullable<decimal> VL_MULTA { get; set; }
        public Nullable<decimal> VL_PAGTO_S_HONO { get; set; }
        public Nullable<decimal> VL_PAGTO_C_HONO { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public Nullable<decimal> VL_TOTAL { get; set; }
        public Nullable<decimal> FT_IND_DESCONTO { get; set; }
        public Nullable<decimal> VL_POR_DIA { get; set; }
        public Nullable<decimal> VL_JUROS { get; set; }
        public Nullable<decimal> FT_IND_BANCO { get; set; }
        public Nullable<decimal> FT_IND_JURIDICO { get; set; }
        public Nullable<decimal> VL_COMISSIONAMENTO { get; set; }
        public Nullable<decimal> VL_COMISS_PERM { get; set; }
        public string VL_TOTAL_GERAL { get; set; }
        public Nullable<int> Expr12 { get; set; }
        public string TX_OBSERVACAO { get; set; }
        public string TX_OBSERVACAO2 { get; set; }
        public string TX_OBSERVACAO3 { get; set; }
        public string AN_TX_CONTRATO { get; set; }
        public Nullable<int> NR_LOTE { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA { get; set; }
        public Nullable<int> FL_IMPRIMIR { get; set; }
        public string CD_USUARIO { get; set; }
        public string AN_CAMPO_1 { get; set; }
        public string AN_DIGITO_1 { get; set; }
        public string AN_CAMPO_2 { get; set; }
        public string AN_DIGITO_2 { get; set; }
        public string AN_CAMPO_3 { get; set; }
        public string AN_DIGITO_3 { get; set; }
        public string AN_DIGITO_GERAL { get; set; }
        public string AN_CODIGO_BARRA { get; set; }
        public string CD_AGENCIA { get; set; }
        public string CD_CEDENTE { get; set; }
        public string NM_CEDENTE { get; set; }
        public string CD_REPR_NUMERICA { get; set; }
        public string IN_TIPO_BLOQUETO { get; set; }
        public string CD_ERRO { get; set; }
        public string AN_DESCR_ERRO { get; set; }
        public Nullable<System.DateTime> DT_RETORNO { get; set; }
        public Nullable<System.DateTime> DT_BOLETO_PAGO { get; set; }
        public string IN_TIPO_COMISS { get; set; }
        public Nullable<int> NR_INCONSISTENCIA { get; set; }
        public Nullable<System.DateTime> DT_CONFIRMA_PAGTO { get; set; }
        public Nullable<int> IN_FAX_TRANSMITIDO { get; set; }
        public string NR_FAX { get; set; }
        public string AN_DESCR_BOLETO { get; set; }
        public string AN_CONTRATOS_BOLETO { get; set; }
        public string AN_PARCELAS_BOLETO { get; set; }
        public string AN_COD_AUTORIZACAO { get; set; }
        public string CD_PROGRAMA { get; set; }
        public Nullable<System.DateTime> Expr13 { get; set; }
        public Nullable<System.DateTime> Expr14 { get; set; }
        public Nullable<System.DateTime> Expr15 { get; set; }
        public string Expr16 { get; set; }
        public string Expr17 { get; set; }
        public string Expr18 { get; set; }
        public Nullable<int> ID_BANCO { get; set; }
        public string CD_BANCO { get; set; }
        public string DS_BANCO { get; set; }
        public string AN_ENDERECO { get; set; }
        public string AN_CIDADE { get; set; }
        public string CD_UF { get; set; }
        public string AN_CNPJ { get; set; }
        public string AN_INS_EST { get; set; }
        public string Expr19 { get; set; }
        public string Expr20 { get; set; }
        public Nullable<decimal> Expr21 { get; set; }
        public Nullable<decimal> Expr22 { get; set; }
        public Nullable<decimal> Expr23 { get; set; }
        public Nullable<decimal> FT_IND_JUROS { get; set; }
        public Nullable<decimal> Expr24 { get; set; }
        public Nullable<decimal> Expr25 { get; set; }
        public Nullable<decimal> Expr26 { get; set; }
        public Nullable<decimal> Expr27 { get; set; }
        public Nullable<int> QT_DIAS_NOTIFICACAO { get; set; }
        public Nullable<int> NR_RECIBO { get; set; }
        public Nullable<int> NR_BOLETO { get; set; }
        public Nullable<int> NR_BORDERO { get; set; }
        public Nullable<int> NR_NOTIFICACAO { get; set; }
        public Nullable<int> Expr28 { get; set; }
        public Nullable<int> QT_DIAS_AJUIZAMENTO { get; set; }
        public Nullable<int> QT_DIAS_CARTORIO { get; set; }
        public Nullable<decimal> VL_META { get; set; }
        public Nullable<decimal> Expr29 { get; set; }
        public Nullable<decimal> Expr30 { get; set; }
        public Nullable<System.DateTime> Expr31 { get; set; }
        public Nullable<System.DateTime> Expr32 { get; set; }
        public string Expr33 { get; set; }
        public string Expr34 { get; set; }
    }
}
